src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
This closes gravitee-io/issues#1329
=> fix: When a token expire we should not log in error

src/main/java/io/gravitee/policy/jwt/key/PublicKeyHelper.java, src/test/java/io/gravitee/policy/jwt/key/PublicKeyHelperTest.java
=> fix(jwt): fix parseSSHPublicKey method to read RS384 keys

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
Closes gravitee-io/issues#3189
=> fix: End user is not logged when a policy fail

pom.xml, src/main/java/io/gravitee/policy/jwt/jwks/CachedJWKSource.java, src/main/java/io/gravitee/policy/jwt/jwks/URLJWKSourceResolver.java, src/test/java/io/gravitee/policy/jwt/jwks/URLJWKSourceResolverTest.java
https://github.com/gravitee-io/issues/issues/6046
JWKS is refreshed from URL every 5 minutes.
If one of those HTTP GET fails, old cached value is kept in cache, and still used.
This avoid JWT validation errors when JWKS URL is temporary unavailable.
Implementation using Guava LoadingCache with a refreshAfterWrite internal does not fit ;
We can't have a unique CacheLoader as we use different ResourceRetriever, some with proxy, some without.
That's what I used a custom cache refresh implementation.
=> feat: improve JWKS refresh from URL

README.adoc, pom.xml, src/main/java/io/gravitee/policy/jwt/jwks/retriever/VertxResourceRetriever.java
see https://github.com/gravitee-io/issues/issues/7739
---
- use it directly by updating your project with version: `2.0.0-refactor-use-commong-proxy-options-factory-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/2.0.0-refactor-use-commong-proxy-options-factory-SNAPSHOT/gravitee-policy-jwt-2.0.0-refactor-use-commong-proxy-options-factory-SNAPSHOT.zip)
=> refactor: use common vertx proxy options factory

pom.xml, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/DefaultJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/GatewayKeysJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/GivenKeyJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JwksUrlJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/utils/TokenExtractor.java
**Issue**
https://github.com/gravitee-io/issues/issues/8009
Update policy to handle new message execution context
---
- use it directly by updating your project with version: `2.2.0-8238-entrypoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/2.2.0-8238-entrypoint-SNAPSHOT/gravitee-policy-jwt-2.2.0-8238-entrypoint-SNAPSHOT.zip)
=> update security policy to be compatible with async reactor

pom.xml
---
- use it directly by updating your project with version: `2.3.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/2.3.0/gravitee-policy-jwt-2.3.0.zip)
=> chore: bump gravitee-parent version

pom.xml, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
Bump gateway api version to use the latest Metric object
---
- use it directly by updating your project with version: `3.0.1-bump-gateway-api-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/3.0.1-bump-gateway-api-version-SNAPSHOT/gravitee-policy-jwt-3.0.1-bump-gateway-api-version-SNAPSHOT.zip)
=> fix: bump version of gateway api

src/test/java/io/gravitee/policy/v3/jwt/JwtPolicyV3IntegrationTest.java
- to avoid giving too much information, all error will only return Unauthorized as message.
---
- use it directly by updating your project with version: `4.0.0-simplify-error-message-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/4.0.0-simplify-error-message-SNAPSHOT/gravitee-policy-jwt-4.0.0-simplify-error-message-SNAPSHOT.zip)
=> fix: simplify unauthorized message

pom.xml
---
- use it directly by updating your project with version: `4.1.1-bump-gravitee-common-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/4.1.1-bump-gravitee-common-version-SNAPSHOT/gravitee-policy-jwt-4.1.1-bump-gravitee-common-version-SNAPSHOT.zip)
=> fix: bump gravitee common version

pom.xml
**Issue**
https://gravitee.atlassian.net/browse/APIM-4028
The library https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on has been moved to https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
The library https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15on has been moved to
https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on
The main goal of this task is to update the library and resolve vulnerability issues:
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6084022
---
- use it directly by updating your project with version: …
=> fix(deps): update bcprov-jdk15on to bcprov-jdk18on 

pom.xml, src/main/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/VertxResourceRetriever.java, src/test/java/io/gravitee/policy/jwt/jwk/AbstractJWKTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-XXXX
Revert 4.1.4 release <- do not use it with version lower or equal to 4.3.x => 4.1.x
---
- use it directly by updating your project with version: `4.1.5-revert-4-1-4-release-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/4.1.5-revert-4-1-4-release-SNAPSHOT/gravitee-policy-jwt-4.1.5-revert-4-1-4-release-SNAPSHOT.zip)
=> Revert do not use 4.1.4 with version lower or equal to 4.3.x => 4.1.x

README.adoc, pom.xml, src/main/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/VertxResourceRetriever.java, src/test/java/io/gravitee/policy/jwt/jwk/AbstractJWKTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-6108
Description
Updated APIM version VertxProxyOptionsUtils was moved to gravitee-node
---
- use it directly by updating your project with version: `5.0.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/5.0.0/gravitee-policy-jwt-5.0.0.zip)
=> fix(dependency): VertxProxyOptionsUtils was moved to gravitee-node

src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JwksUrlJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/JWTPolicyV3.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/URLJWKSourceResolver.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/RetrieveOptions.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/processor/AbstractKeyProcessor.java, src/main/resources/schemas/schema-form.json
see https://gravitee.atlassian.net/browse/APIM-7292
---
- use it directly by updating your project with version: `3.1.0-apim-7292-set-jwks-timeouts-3-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/3.1.0-apim-7292-set-jwks-timeouts-3-x-SNAPSHOT/gravitee-policy-jwt-3.1.0-apim-7292-set-jwks-timeouts-3-x-SNAPSHOT.zip)
=> feat: make jwks timeouts configurable (3.x)

src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JwksUrlJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/JWTPolicyV3.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/URLJWKSourceResolver.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/RetrieveOptions.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/processor/AbstractKeyProcessor.java, src/main/resources/schemas/schema-form.json
see https://gravitee.atlassian.net/browse/APIM-7292
---
- use it directly by updating your project with version: `4.2.0-apim-7292-set-jwks-timeouts-4-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/4.2.0-apim-7292-set-jwks-timeouts-4-x-SNAPSHOT/gravitee-policy-jwt-4.2.0-apim-7292-set-jwks-timeouts-4-x-SNAPSHOT.zip)
=> feat: make jwks timeouts configurable (4.x)

src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JwksUrlJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/JWTPolicyV3.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/URLJWKSourceResolver.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/RetrieveOptions.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/processor/AbstractKeyProcessor.java, src/main/resources/schemas/schema-form.json
see https://gravitee.atlassian.net/browse/APIM-7292
---
- use it directly by updating your project with version: `5.1.0-apim-7292-set-jwks-timeouts-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/5.1.0-apim-7292-set-jwks-timeouts-SNAPSHOT/gravitee-policy-jwt-5.1.0-apim-7292-set-jwks-timeouts-SNAPSHOT.zip)
=> feat: make jwks timeouts configurable (5.x)

src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/GatewayKeysJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/GivenKeyJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JwksUrlJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/utils/TokenTypeVerifierFactory.java, src/main/resources/schemas/schema-form.json, src/test/java/io/gravitee/policy/jwt/JwtPolicyV4EmulationEngineCustomTokenTypIntegrationTest.java, src/test/java/io/gravitee/policy/jwt/utils/TokenTypeVerifierFactoryTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7273
---
- use it directly by updating your project with version: `5.2.0-apim-7273-accept-at-jwt-token-typ-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/5.2.0-apim-7273-accept-at-jwt-token-typ-SNAPSHOT/gravitee-policy-jwt-5.2.0-apim-7273-accept-at-jwt-token-typ-SNAPSHOT.zip)
=> feat: support custom token type header

.circleci/config.yml, .github/pull_request_template.md, .github/renovate.json, pom.xml, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/DefaultJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/GatewayKeysJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/GivenKeyJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JwksUrlJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/jwt/utils/TokenExtractor.java, src/main/java/io/gravitee/policy/v3/jwt/JWTPolicyV3.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/hmac/MACJWKSourceResolver.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/rsa/RSAJWKSourceResolver.java, src/main/java/io/gravitee/policy/v3/jwt/resolver/GatewaySignatureKeyResolver.java, src/main/java/io/gravitee/policy/v3/jwt/resolver/SignatureKeyResolver.java, src/main/java/io/gravitee/policy/v3/jwt/resolver/TemplatableSignatureKeyResolver.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java, src/test/java/io/gravitee/policy/jwt/jwk/AbstractJWKTest.java, src/test/java/io/gravitee/policy/jwt/jwk/provider/DefaultJWTProcessorProviderTest.java, src/test/java/io/gravitee/policy/jwt/jwk/provider/GatewayKeysJWTProcessorProviderTest.java, src/test/java/io/gravitee/policy/jwt/jwk/provider/GivenKeyJWTProcessorProviderTest.java, src/test/java/io/gravitee/policy/jwt/jwk/provider/JwksUrlJWTProcessorProviderTest.java, src/test/java/io/gravitee/policy/jwt/utils/TokenExtractorTest.java, src/test/java/io/gravitee/policy/v3/jwt/JWTPolicyV3Test.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7143
- use new HttpSecurityPolicy and BaseExecutionContext interface (BREAKING CHANGE: requires APIM 4.6+)
- implement kafka policy
---
- use it directly by updating your project with version: `6.0.0-apim-7143-impl-security-chain-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/6.0.0-apim-7143-impl-security-chain-SNAPSHOT/gravitee-policy-jwt-6.0.0-apim-7143-impl-security-chain-SNAPSHOT.zip)
=> Update policy for kafka gateway

README.adoc, src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/java/io/gravitee/policy/jwt/jwk/provider/JwksUrlJWTProcessorProvider.java, src/main/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetriever.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/RetrieveOptions.java, src/main/java/io/gravitee/policy/v3/jwt/jwks/retriever/VertxResourceRetriever.java, src/main/resources/schemas/schema-form.json, src/test/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetrieverTest.java, src/test/java/io/gravitee/policy/v3/jwt/jwks/retriever/VertxResourceRetrieverTest.java
https://gravitee.atlassian.net/browse/APIM-8921
This PR brings the capability to follow HTTP redirects when fetching remote JWKS.
---
- use it directly by updating your project with version: `6.1.0-apim-8921-support-follow-http-redirects-fetching-jwks-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/6.1.0-apim-8921-support-follow-http-redirects-fetching-jwks-SNAPSHOT/gravitee-policy-jwt-6.1.0-apim-8921-support-follow-http-redirects-fetching-jwks-SNAPSHOT.zip)
=> feat: add option to follow http redirects

.circleci/config.yml, src/main/java/io/gravitee/policy/jwt/jwk/provider/GatewayKeysJWTProcessorProvider.java
APIM-8036
https://gravitee.atlassian.net/browse/APIM-8036
Force property resolution by using the getProperty method to ensure that environment variables are considered.
---
- use it directly by updating your project with version: `5.1.1-APIM-8036-resolve-gateway-keys5-1-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/5.1.1-APIM-8036-resolve-gateway-keys5-1-x-SNAPSHOT/gravitee-policy-jwt-5.1.1-APIM-8036-resolve-gateway-keys5-1-x-SNAPSHOT.zip)
=> fix: Properly resolve property value

src/main/java/io/gravitee/policy/v3/jwt/JWTPolicyV3.java
https://gravitee.atlassian.net/browse/APIM-9171
Make sure that the followHttpRedirects option is taken into account for v2 API.
---
- use it directly by updating your project with version: `6.1.2-apim-9171-fix-follow-redirects-on-v2-apis-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/6.1.2-apim-9171-fix-follow-redirects-on-v2-apis-SNAPSHOT/gravitee-policy-jwt-6.1.2-apim-9171-fix-follow-redirects-on-v2-apis-SNAPSHOT.zip)
=> fix: follow http redirect on v2 api

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
n/a
---
- use it directly by updating your project with version: `6.1.4-refactor-context-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/6.1.4-refactor-context-SNAPSHOT/gravitee-policy-jwt-6.1.4-refactor-context-SNAPSHOT.zip)
=> fix: condition `.metrics()` use only if ctx is http

src/main/java/io/gravitee/policy/jwt/jwk/source/VertxResourceRetriever.java
The JWKS retriever is configured to allow trust_all support for HTTPS URL.
This was the behavior for v2 APIs which has not been migrated to v4 APIs.
---
- use it directly by updating your project with version: `6.1.5-trust-all-support-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/6.1.5-trust-all-support-SNAPSHOT/gravitee-policy-jwt-6.1.5-trust-all-support-SNAPSHOT.zip)
=> fix: Add support for trust_all
