gravitee-io/gravitee-policy-jwt

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/main/resources/schemas/schema-form.json
=> fix(jwt): Public key resolver is required

pom.xml, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
=> fix(gateway): Update model to handle multiple values per query parameter

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
=> feat(oauth2): Manage OAuth2 and JWT plan security type

pom.xml, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
=> Unsigned JWT

pom.xml, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/java/io/gravitee/policy/jwt/configuration/KeyResolver.java, src/main/java/io/gravitee/policy/jwt/jwks/JWKSourceResolver.java, src/main/java/io/gravitee/policy/jwt/jwks/PublicKeyJWKSourceResolver.java, src/main/java/io/gravitee/policy/jwt/key/GatewayPublicKeyResolver.java, src/main/java/io/gravitee/policy/jwt/key/PublicKeyHelper.java, src/main/java/io/gravitee/policy/jwt/key/PublicKeyResolver.java, src/main/java/io/gravitee/policy/jwt/key/TemplatablePublicKeyResolver.java, src/main/java/io/gravitee/policy/jwt/key/UserDefinedPublicKeyResolver.java, src/main/java/io/gravitee/policy/jwt/processor/AbstractKeyProcessor.java, src/main/java/io/gravitee/policy/jwt/processor/KeyProcessor.java, src/main/java/io/gravitee/policy/jwt/processor/PublicKeyKeyProcessor.java, src/main/resources/schemas/schema-form.json, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
Closes gravitee-io/issues#1672
=> feat(jwt): Moving from jjwt to nimbus

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
=> Apply "provide more logs about request context" for nimbus jwt policy version

pom.xml, src/main/java/io/gravitee/policy/jwt/resolver/TemplatableSignatureKeyResolver.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
And move dependency to Gravitee EL
Closes gravitee-io/issues#1987
=> chore: Remove deprecated Gateway EL module

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
This closes gravitee-io/issues#1948
=> feat: Audit on API user from JWT

README.adoc, pom.xml, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
closes gravitee-io/issues#2208
=> Feat: Add response template keys

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
Closes gravitee-io/issues#2486
=> fix(jwt): Header propagation is done after the token has been validated

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/resources/schemas/schema-form.json
=> feat: Allows to override the claim to read for the log of the end user

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
Closes gravitee-io/issues#3189
=> fix: End user is not logged when a policy fail

src/main/java/io/gravitee/policy/jwt/token/TokenExtractor.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java, src/test/java/io/gravitee/policy/jwt/token/TokenExtractorTest.java
According to https://tools.ietf.org/html/rfc6749#section-7.1
Closess gravitee-io/issues#3250
=> fix(jwt): Bearer token_type is case insensitive

README.adoc, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/java/io/gravitee/policy/jwt/jwks/retriever/VertxResourceRetriever.java, src/main/resources/schemas/schema-form.json
Closes gravitee-io/issues#4254
=> feat(proxy): allow jwks resolution behind system proxy

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
=> refactor(policy-jwt): add api_id to log output for improve debugging

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
=> fix(policy): return error in JWT processing exception

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
=> fix(logging): Add API ID into the MDC

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/main/java/io/gravitee/policy/jwt/jwks/URLJWKSourceResolver.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
=> fix(el): support el for jwks url in resolver parameter

README.adoc, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/main/java/io/gravitee/policy/jwt/configuration/JWTPolicyConfiguration.java, src/main/resources/schemas/schema-form.json, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java
Fixes https://github.com/gravitee-io/issues/issues/4900
=> feat: allow to configure client id claims

README.adoc, src/main/resources/schemas/schema-form.json
Adding information about client_id claim.
Fixes gravitee-io/issues#5374
=> doc: improve policy documentation

pom.xml, src/main/java/io/gravitee/policy/jwt/token/TokenExtractor.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java, src/test/java/io/gravitee/policy/jwt/token/TokenExtractorTest.java
Closes gravitee-io/issues#6772
=> feat(headers): Internal rework and introduce HTTP Headers API

.circleci/config.yml
**Issue**
The release is failing because is using an old version of the CI Orb
Update orb version
=> Update orb version

pom.xml, src/main/java/io/gravitee/policy/jwt/JWTPolicy.java, src/test/java/io/gravitee/policy/jwt/JWTPolicyTest.java, src/test/java/io/gravitee/policy/jwt/JwtPolicyIntegrationTest.java, src/test/java/io/gravitee/policy/jwt/JwtPolicyV3CompatibilityIntegrationTest.java, src/test/java/io/gravitee/policy/v3/jwt/JwtPolicyV3IntegrationTest.java, src/test/resources/apis/jwt.json
**Issue**
https://github.com/gravitee-io/issues/issues/7991
---
- use it directly by updating your project with version: `2.3.0-feat-jupiterPlans-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/2.3.0-feat-jupiterPlans-SNAPSHOT/gravitee-policy-jwt-2.3.0-feat-jupiterPlans-SNAPSHOT.zip)
=> feat: migrate to the new version of Jupiter's SecurityPolicy

src/main/java/io/gravitee/policy/jwt/jwk/provider/DefaultJWTProcessorProvider.java, src/test/java/io/gravitee/policy/jwt/jwk/provider/DefaultJWTProcessorProviderTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-4719
configuration for GATEWAY_KEYS keys is stored in the gravitee.yml file. 
when key resolver is GATEWAY_KEYS the resolverParameter can be left empty and there was NPE when store in cache 
GatewayKeysJWTProcessorProvider contains all keys from gravitee.yml so it's ok to store this JWTProcessor under GATEWAY_KEYS key in the cache 
---
- use it directly by updating your project with version: `4.1.3-APIM-4719-geteway-keys-error-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/po …
=> fix(gateway-keys): when using gateway keys resolverParameter should be ignored

src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-7143
Set a max value for kafka token lifetime.
It's required to avoid kafka client re-authent storm
---
- use it directly by updating your project with version: `6.0.0-set-a-max-lifetime-for-kafka-outhbearer-token-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-jwt/6.0.0-set-a-max-lifetime-for-kafka-outhbearer-token-SNAPSHOT/gravitee-policy-jwt-6.0.0-set-a-max-lifetime-for-kafka-outhbearer-token-SNAPSHOT.zip)
=> feat: set a max value for kafka token lifetime

.circleci/config.yml, src/main/java/io/gravitee/policy/jwt/jwk/provider/GatewayKeysJWTProcessorProvider.java
https://gravitee.atlassian.net/browse/APIM-8036
Force property resolution by using the getProperty method to ensure that environment variables are considered.
=> fix: Properly resolve property value
